---

- name: Test if distribution is RedHat
  assert:
    that: ansible_os_family == "RedHat" and
          ansible_distribution_major_version | int >= 6

- name: Yum install Uchiwa dashboard 
  yum:
    name: uchiwa
    state: latest

- name: Copy Uchiwa configuration file over
  template:
    src: uchiwa.json.j2
    dest: "{{ sensu_config_dir }}/uchiwa.json"
  notify:
    - restart_uchiwa

- name: start_uchiwa
  service:
    name: uchiwa
    enabled: yes
    state: started
