---

- name: Test if distribution is RedHat
  assert:
    that: >
      ansible_os_family == "RedHat" and
      ansible_distribution_major_version | int <= 6

- name: Install Uchiwa
  yum:
    name: "{{ uchiwa_pkg }}"
    state: installed

- name: Configure Uchiwa
  template:
    src: uchiwa.json.j2
    dest: "/etc/sensu/uchiwa.json"
  notify: Restart uchiwa

- name: Make sure uchiva service is enabled and started
  service:
    name: uchiwa
    enabled: yes
    state: started
